### ISSUE TITLE
The text on the Hide and Reveal Answers button looks reversed.

### ISSUE THREAD

**Issue by shalluv** [tinarskii/MukPakPak#3]
Now if we press <img width="89" alt="image" src="https://user-images.githubusercontent.com/42491719/173193822-07be945e-6e3f-4691-b728-1900b16ac685.png"> It'll reveal the answer. 

On the other hand, if we press <img width="81" alt="image" src="https://user-images.githubusercontent.com/42491719/173193803-7964ab86-0b9b-4246-ac15-611c2a903c74.png"> It'll hide the answer.

**Comment by tinarskii** [comment]
just fixed k thx
